# Generated by Django 3.2.4 on 2022-01-27 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=False)),
                ('order_for_wp', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('order_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='orders.order')),
                ('order_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='products.products')),
            ],
        ),
        migrations.CreateModel(
            name='SinglePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('of_orderitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='single_orderitem', to='orders.orderitem')),
                ('single_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='single_product', to='products.products')),
            ],
        ),
        migrations.CreateModel(
            name='MyshoppingRecent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopping_in', models.CharField(choices=[('pp', 'paypal'), ('wp', 'whatsapp')], max_length=100)),
                ('shopping_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopping', to='orders.order')),
                ('shopping_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_user', to=settings.AUTH_USER_MODEL)),
                ('singlepurchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='single_purchase', to='orders.singlepurchase')),
            ],
        ),
    ]
